server:
  port: 8443
  ssl:
    key-store: classpath:sample.jks
    key-store-password: secret
    key-password: password
#    client-auth: NEED

grid:
  idpUrl: https://unity.grid.icm.edu.pl/testbed-portal/saml2unicoreIdp-web
  targetUrl: https://localhost:8443/oxides/authn
#  targetUrl: https://alfred.mat.umk.pl:8443/authn/saml
